# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-lambda-live-tuner" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "83ab2c2afde14882b8a7e3a329093e6709b2bb83d6f47cdb34f44062e5d4fef6"
      url "https://github.com/janritter/aws-lambda-live-tuner/releases/download/#{version}/aws-lambda-live-tuner_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09d122c1f8b43bc46c7c6004b7c6cd7e3769d3ecacf3b13ec416c84b91598f41"
      url "https://github.com/janritter/aws-lambda-live-tuner/releases/download/#{version}/aws-lambda-live-tuner_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e4eb6e3ec563b0f39c002ea062d4bc90070cd9bf73dcb50b2a0604e11740c912"
      url "https://github.com/janritter/aws-lambda-live-tuner/releases/download/#{version}/aws-lambda-live-tuner_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1eeb2829fb56e4106b3b679f8ca065b28d9d1343b0fe1d3c9e51423d1cf4a8c1"
      url "https://github.com/janritter/aws-lambda-live-tuner/releases/download/#{version}/aws-lambda-live-tuner_#{version}_linux_amd64.tar.gz"
    end
  end

  name "aws-lambda-live-tuner"
  desc "Tool to optimize Lambda functions on real incoming events"
  homepage "https://github.com/janritter/aws-lambda-live-tuner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-lambda-live-tuner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aws-lambda-live-tuner"]
    end
  end

  # No zap stanza required
end
